/*
 * Copyright (c) 2018 Absa Bank Limited, All Rights Reserved.
 *
 * This code is confidential to Absa Bank Limited and shall not be disclosed
 * outside the Bank without the prior written permission of the Absa Legal
 *
 * In the event that such disclosure is permitted the code shall not be copied
 * or distributed other than on a need-to-know basis and any recipients may be
 * required to sign a confidentiality undertaking in favor of Absa Bank
 * Limited
 *
 */
package com.barclays.absa.banking.payments.international.services

interface WesternUnionParameters {
    companion object {
        const val SERVICE_BENEFICIARY_CITY = "beneficiaryCity"
        const val SERVICE_BENEFICIARY_COUNTRY = "beneficiaryCountry"
        const val SERVICE_BENEFICIARY_GENDER = "gender"
        const val SERVICE_BENEFICIARY_STATE = "beneficiaryState"
        const val SERVICE_BENEFICIARY_STREET_ADDRESS = "beneficiaryStreetAddress"
        const val SERVICE_BENEFICIARY_SHORT_NAME = "beneficiaryShortName"
        const val SERVICE_BENEFICIARY_RESIDENTIAL_STATUS = "nonResidentAccountIdentifier"
        const val SERVICE_BENEFICIARY_SURNAME = "benSurname"
        const val SERVICE_PAYMENT_TYPE = "paymentType"
        const val STATE_NAME = "stateName"
        const val NORMAL = "normal"
        const val INDIVIDUAL = "individual"
        const val SERVICE_TRANSACTION_REFERENCE_ID = "txnRefId"
        const val SERVICE_BENEFICIARY_TYPE = "beneficiaryType"
        const val SERVICE_BENEFICIARY_TYPE_WESTERN_UNION = "transferTypeResult"
        const val SERVICE_FOREIGN_CURRENCY = "foreignCurrencyWithZAR"
        const val SERVICE_WU_BENEFICIARY_NUMBER = "wuBeneficiaryNumber"
        const val SERVICE_TRANSFER_TYPE = "transferType"
        const val SERVICE_COUNTRY_CODE = "countryCode"
        const val WESTERN_UNION = "WesternUnion"
        const val SERVICE_VALIDATE_PAYMENT_TRANSFER_TYPE = "transferType"
        const val SERVICE_VALIDATE_PAYMENT_ENTITY_TYPE = "entityType"
        const val SERVICE_VALIDATE_PAYMENT_TRANSACTION_REFERENCE_NUMBER = "transactionReferenceNumber"
        const val SERVICE_VALIDATE_PAYMENT_FOREIGN_CURRENCY = "foreignCurrency"
        const val SERVICE_VALIDATE_PAYMENT_FOREIGN_AMOUNT = "foreignAmount"
        const val SERVICE_VALIDATE_PAYMENT_USD_CONVERSION_RATE = "usdConversionRate"
        const val SERVICE_VALIDATE_PAYMENT_EXPECTED_PAYOUT_CURRENCY = "expectedPayoutCurrency"
        const val SERVICE_VALIDATE_PAYMENT_EXPECTED_PAYOUT_AMOUNT = "expectedPayoutAmount"
        const val SERVICE_VALIDATE_PAYMENT_DESTINATION_CURRENCY_RATE = "destinationCurrencyRate"
        const val SERVICE_VALIDATE_PAYMENT_LOCAL_CURRENCY = "localCurrency"
        const val SERVICE_VALIDATE_PAYMENT_LOCAL_AMOUNT = "localAmount"
        const val SERVICE_VALIDATE_PAYMENT_COMMISSION_AMOUNT_FEE = "commissionAmountFee"
        const val SERVICE_VALIDATE_PAYMENT_VAT_AMOUNT = "vatAmount"
        const val SERVICE_VALIDATE_PAYMENT_TOTAL_DUE = "totalDue"
        const val SERVICE_VALIDATE_PAYMENT_FROM_ACCOUNT = "fromAccount"
        const val SERVICE_VALIDATE_PAYMENT_SENDER_FIRST_NAME = "senderFirstName"
        const val SERVICE_VALIDATE_PAYMENT_SENDER_SURNAME = "senderSurname"
        const val SERVICE_VALIDATE_PAYMENT_RECEIVER_FIRST_NAME = "receiverFirstName"
        const val SERVICE_VALIDATE_PAYMENT_RECEIVER_SURNAME = "receiverSurname"
        const val SERVICE_VALIDATE_PAYMENT_MTCN_CODE = "mtcnCode"
        const val SERVICE_VALIDATE_PAYMENT_DESTINATION_COUNTRY = "destinationCountry"
        const val SERVICE_VALIDATE_PAYMENT_DESTINATION_STATE = "destinationState"
        const val SERVICE_VALIDATE_PAYMENT_DESTINATION_CITY = "destinationCity"
        const val SERVICE_VALIDATE_PAYMENT_ORIGINATING_COUNTRY = "originatingCountry"
        const val SERVICE_VALIDATE_PAYMENT_RESIDING_COUNTRY = "residingCountry"
        const val SERVICE_VALIDATE_PAYMENT_RESIDING_COUNTRY_DESCRIPTION = "residingCountryDescription"
        const val SERVICE_VALIDATE_PAYMENT_RESIDING_STATE = "residingState"
        const val SERVICE_VALIDATE_PAYMENT_RESIDING_CITY = "residingCity"
        const val SERVICE_VALIDATE_PAYMENT_STREET_ADDRESS = "streetAddress"
        const val SERVICE_VALIDATE_PAYMENT_DOCUMENT_SOURCE_IND = "documentSourceInd"
        const val SERVICE_VALIDATE_PAYMENT_DOCUMENT_BEND_ID = "bendId"
        const val SERVICE_VALIDATE_PAYMENT_BENEFICIARY_IFT_TYPE = "beneficiaryIFTType"
        const val SERVICE_VALIDATE_PAYMENT_BENEFICIARY_FIRST_NAME = "beneficiaryFirstName"
        const val SERVICE_VALIDATE_PAYMENT_BENEFICIARY_SURNAME = "beneficiarySurname"
        const val SERVICE_VALIDATE_PAYMENT_BENEFICIARY_ACCOUNT_NUMBER = "beneficiaryAccountNo"
        const val SERVICE_VALIDATE_PAYMENT_BENEFICIARY_ACCOUNT_TYPE = "beneficiaryAccountType"
        const val SERVICE_VALIDATE_PAYMENT_BENEFICIARY_REFERENCE = "beneficiaryReference"
        const val SERVICE_VALIDATE_PAYMENT_BENEFICIARY_STATUS = "beneficiaryStatus"
        const val SERVICE_VALIDATE_PAYMENT_BENEFICIARY_EFT_NUMBER = "beneficiaryEftNumber"
        const val SERVICE_VALIDATE_PAYMENT_BENEFICIARY_TIEB_NUMBER = "beneficiaryTiebNumber"
        const val SERVICE_VALIDATE_PAYMENT_BENEFICIARY_CIF_KEY = "beneficiaryCifkey"
        const val SERVICE_VALIDATE_PAYMENT_BENEFICIARY_COUNTRY_CODE = "beneficiaryCountryCode"
        const val SERVICE_VALIDATE_PAYMENT_BENEFICIARY_STATE_NAME = "beneficiaryStateName"
        const val SERVICE_VALIDATE_PAYMENT_BENEFICIARY_CITY_NAME = "beneficiaryCityName"
        const val SERVICE_VALIDATE_PAYMENT_BENEFICIARY_ISO_COUNTRY_CODE = "beneficiaryIsoCountryCode"
        const val SERVICE_VALIDATE_PAYMENT_BENEFICIARY_GENDER = "beneficiaryGender"
        const val SERVICE_VALIDATE_PAYMENT_FOREIGN_CURRENCY_WITH_ZAR = "foreignCurrencyWithZAR"
        const val OUT = "OUT"
        const val SERVICE_BENEFICIARY_NUMBER = "beneficiaryNumber"
        const val SERVICE_AVAILABLE_BALANCE = "availableBalance"
        const val SERVICE_RULING_CODE = "rulingCode"
        const val SERVICE_SEND_CURRENCY = "sendCurrency"
        const val SERVICE_CITY = "city"
        const val SERVICE_STREET_ADDRESS = "streetAddress"
        const val SERVICE_BENEFICIARY_IFT_TYPE = "beneficiaryIFTType"
        const val SERVICE_ID = "id"
        const val SERVICE_STATUS = "status"
        const val SERIVCE_EFT_NUMBER = "eftNumber"
        const val SERVICE_CIF_KEY = "cifkey"
        const val SERVICE_TIEB_NUMBER = "tiebNumber"
        const val SERVICE_BOP_CATEGORY_CODE = "bopCategoryCode"
        const val SERVICE_BOP_SUB_CATEGORY = "bopSubCategory"
        const val SERVICE_FLOW = "flow"
        const val SERVICE_TYPE_OF_PAYMENT = "typeOfPayment"
        const val SERVICE_FROM_ACCOUNT_NUMBER = "fromAccountNumber"
        const val SERVICE_RECEIVING_BANK = "receivingBank"
        const val SERVICE_VALUE_DATE = "valueDate"
        const val SERVICE_TRANSACTION_TYPE = "transactionType"
        const val SERVICE_BENEFICIARY_NAME = "beneficiaryName"
        const val SERVICE_BENEFICIARY_SUR_NAME = "beneficiarySurName"
        const val SERVICE_AMOUNT = "amount"
        const val SERVICE_BENEFICIARY_ACCOUNT_NUMBER = "beneficiaryAccountNumber"
        const val BOP_CATEGORY_CODE_VALUE = "401"
        const val BOP_SUB_CATEGORY_VALUE = "80"
        const val RULING_CODE_VALUE = "B.4(A)(x)"
        const val TYPE_OF_PAYMENT_VALUE = "P2P"
        const val RECEIVING_BANK_VALUE = "WU Bank"
        const val MALE = "M"
        const val TRANSACTION_REFERENCE_ID = "transaction_reference_id"
        const val SERVICE_STATE = "state"
        const val SERVICE_DESTINATION_STATE = "destinationState"
        const val SERVICE_BENEFICIARY_PAYMENT_TYPE = "beneficiaryPaymentType"
        const val SERVICE_BENEFICIARY_COUNTRY_DESCRIPTION = "beneficiaryCountryDescription"
        const val EMAIL = "Email"
        const val SERVICE_TEST_QUESTION = "testQuestion"
        const val SERVICE_TEST_ANSWER = "testAnswer"
        const val NON_RESIDENT_OTHER = "NON RESIDENT OTHER"
        const val RES_FOREIGN_BANK_ACCOUNT = "RES FOREIGN BANK ACCOUNT"
        const val CURRENCY_CODE = "currencyCode"
        const val AMOUNT_ENTERED = "amountEntered"
        const val GENDER = "gender"
        const val COUNTRY = "country"
        const val NOT_AVAILABLE = "NA"
        const val ONCE_OFF_PAYMENT = "onceOff"
        const val DISPLAY_QUESTIONS_AND_ANSWERS = "displayQuestionsAndAwnsers"
        const val CURRENT = "CURRENT"
        const val BENEFICIARY_SURNAME = "beneficiarySurname"
        const val BENEFICIARY_COUNTRY = "benCountry"
    }
}