#logging:
#    level:
#        org:
#            hibernate:
#                SQL: DEBUG
#                type: trace
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: monster123
        url: jdbc:postgresql://debtybackdb.cdr3c8itgucr.us-east-1.rds.amazonaws.com:5432/debty
        username: rasmus

    jpa:
        properties:
            temp:
                use_jdbc_metadata_defaults: false
            hibernate:
                ddl-auto: validate
                dialect: org.hibernate.dialect.PostgreSQLDialect
             #   format_sql: true
             #   show_sql: true
             #   use_sql_comments: true
        generate-ddl: true

security:
    oauth2:
        client:
            clientId: 233668646673605
            clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
            accessTokenUri: https://graph.facebook.com/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
        resource:
            userInfoUri: https://graph.facebook.com/me
